services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5teamPunk
      POSTGRES_DB: f1
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db/f1_dump.sql:/docker-entrypoint-initdb.d/f1_dump.sql

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:5teamPunk@db:5432/f1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  db-data: