### Get the next race 
GET http://localhost:3001/api/races/next

### Get all the drivers
GET http://localhost:3001/api/driver

### Get current standings
GET http://localhost:3001/api/currentStandings

### test drivers standings 
Get http://localhost:3001/api/currentStandingsTest

### test
GET http://localhost:3001/people.json