### Get the next race 
GET http://localhost:3001/api/races/next

### Get specific driverstandings per year
GET http://localhost:3001/api/driverstandings?year=2024

### test drivers standings 
Get http://localhost:3001/api/currentStandingsTest

### See what result for last race in a season per year returns
Get http://localhost:3001/api/driverStandings?year=2021


//################### CORE ################################//

### driver
GET http://localhost:3001/api/driver?id=1

### driver all
GET http://localhost:3001/api/driver


### constructor
GET http://localhost:3001/api/constructor?id=1

### constructor all
GET http://localhost:3001/api/constructor


### circuit
GET http://localhost:3001/api/circuit?id=1

### circuit all
GET http://localhost:3001/api/circuit

//#########################################################//